---
title: "Rendu 1"
output: html_document
---

```{r setup, include=FALSE}
Database <- read.table("Data/tree-moisture.txt", header = FALSE)
Database
names(Database) <- c("Species", "Branch_Species", "Branch_Locations", "Transpiration_Types", "Dry")


Database$Species <- factor(c("Lobolly Pine","Shortleaf Pine", "Yellow Poplar","Red Gum"))
Database$Branch_Locations <- factor(c("Central", "Distal", "Proximal"))
Database$Transpiration_Types <- factor(c("Rapid", "Slow"))

tapply(Database$Dry, list(Database$Species, Database$Transpiration_Types, Database$Branch_Locations), mean) 
tapply(Database$Dry, list(Database$Species, Database$Transpiration_Types, Database$Branch_Locations), sd) 
plot.design(Database) 
show()
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
moisture.aov <- aov(Dry ~ Species*Branch_Locations, data=Database)
summary(moisture.aov)
coef(moisture.aov)
options("contrasts")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r pressure, echo=FALSE}
interaction.plot(Database$Branch_Locations,Database$Species, Database$Dry)
```

```{r pressure, echo=FALSE}
layout(matrix(1:4,ncol=2)) 
plot(moisture.aov)
```